"""
Test script for QuizGenerationService
"""
import sys
import os
import logging

# Add parent directory to path
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from services.quiz_generation import QuizGenerationService
from services.rag.rag_service import RagService

# Configure logging for test
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    handlers=[
        logging.StreamHandler(),
        logging.FileHandler('logs/test_quiz_generation.log', encoding='utf-8')
    ]
)

logger = logging.getLogger(__name__)

def test_quiz_generation():
    """Test the quiz generation workflow"""
    logger.info("===============================================")
    logger.info("STARTING QUIZ GENERATION TEST")
    logger.info("===============================================")
    print("=== Testing Quiz Generation Service ===")
    
    try:
        # Initialize RAG service
        logger.info("Step 1: Initializing RAG service...")
        print("1. Initializing RAG service...")
        rag_service = RagService()
        logger.info("RAG service initialized successfully")
        
        # Initialize Quiz service
        logger.info("Step 2: Initializing Quiz Generation service...")
        print("2. Initializing Quiz Generation service...")
        quiz_service = QuizGenerationService(rag_service)
        logger.info("Quiz Generation service initialized successfully")
        
        # Test data
        document_id = "test_doc_1"
        user_request = "Tạo bộ đê kiểm tra gồm 5 câu hỏi tự luận về khoa điện tử viễn thông của trường ĐH Khoa Học Tự Nhiên, ĐHQG-HCM"
        toc_data = dummy_table_of_contents()
        
        logger.info(f"Test parameters:")
        logger.info(f"  - Document ID: {document_id}")
        logger.info(f"  - User request: {user_request}")
        logger.info(f"  - TOC data length: {len(toc_data)} characters")

        logger.info("Step 3: Running quiz generation workflow...")
        print("3. Running quiz generation workflow...")
        result = quiz_service.generate_quiz_set(
            document_id=document_id,
            user_request=user_request,
            toc_data=toc_data
        )
        logger.info("Quiz generation workflow completed")
        
        # Log detailed results
        logger.info("Step 4: Analyzing results...")
        print("4. Results:")
        
        document_id_result = result.get('document_id')
        section_tasks = result.get('section_tasks', [])
        generated_questions = result.get('generated_questions', [])
        final_questions = result.get('final_questions', [])
        
        logger.info(f"Results analysis:")
        logger.info(f"  - Document ID: {document_id_result}")
        logger.info(f"  - Number of section tasks: {len(section_tasks)}")
        logger.info(f"  - Number of generated question groups: {len(generated_questions)}")
        logger.info(f"  - Number of final questions: {len(final_questions)}")
        
        print(f"   - Document ID: {document_id_result}")
        print(f"   - Section tasks: {len(section_tasks)}")
        print(f"   - Generated questions: {len(generated_questions)}")
        print(f"   - Final questions: {len(final_questions)}")
        
        # Log section tasks details
        logger.info("Section tasks details:")
        for i, task in enumerate(section_tasks):
            task_info = f"Task {i+1}: {task.get('section_title', 'N/A')} - {task.get('number_of_questions', 0)} questions"
            logger.info(f"  {task_info}")
        
        # Log generated questions details
        logger.info("Generated questions details:")
        for i, gen_q in enumerate(generated_questions):
            gen_info = f"Section {i+1}: {gen_q.get('section_title', 'N/A')} - {len(gen_q.get('questions', []))} questions generated"
            logger.info(f"  {gen_info}")
        
        # Print sample questions
        if final_questions:
            logger.info("Sample questions (first 2):")
            print("\n5. Sample questions:")
            for i, q in enumerate(final_questions[:2]):  # Show first 2
                question_text = q.get('question', 'N/A')
                print(f"   Q{i+1}: {question_text}")
                logger.info(f"  Q{i+1}: {question_text[:100]}..." if len(question_text) > 100 else f"  Q{i+1}: {question_text}")
                print()
        
        logger.info("✅ Test completed successfully!")
        print("✅ Test completed successfully!")
        return True
        
    except Exception as e:
        error_msg = f"❌ Test failed with error: {e}"
        logger.error(error_msg)
        print(error_msg)
        import traceback
        traceback_str = traceback.format_exc()
        logger.error(f"Full traceback:\n{traceback_str}")
        traceback.print_exc()
        return False

def dummy_table_of_contents():
    return """1 TỔNG QUAN VỀ TRƯỜNG ĐẠI HỌC KHOA HỌC TỰ NHIÊN, ĐHQG-HCM (Page 3)
1.1 SỨ MẠNG, TẦM NHÌN, TRIẾT LÝ GIÁO DỤC (Page 3)
1.1.1 SỨ MẠNG (Page 3)
1.1.2 TẦM NHÌN 2030 (Page 3)
1.2 GIÁ TRỊ CỐT LÕI (Page 4)
1.3 QUÁ TRÌNH PHÁT TRIỂN (Page 5)
2 CÁC PHÒNG BAN CHỨC NĂNG, THƯ VIỆN (Page 7)
2.1 PHÒNG ĐÀO TẠO (Page 7)
2.2 PHÒNG CÔNG TÁC SINH VIÊN (Page 8)
2.3 PHÒNG KHẢO THÍ VÀ ĐẢM BẢO CHẤT LƯỢNG (Page 9)
2.3.1 Công tác khảo thí (Page 9)
2.3.2 Công tác đảm bảo chất lượng (Page 9)
2.4 PHÒNG THÔNG TIN - TRUYỀN THÔNG (Page 10)
2.5 PHÒNG THANH TRA - PHÁP CHẾ (Page 11)
2.5.1 Công tác Thanh tra (Page 11)
2.5.2 Công tác Pháp chế (Page 11)
2.5.3 Công tác Sở hữu trí tuệ (Page 11)
2.6 PHÒNG KHOA HỌC CÔNG NGHỆ (Page 12)
2.7 PHÒNG QUAN HỆ ĐỐI NGOẠI (Page 13)
2.8 PHÒNG KẾ HOẠCH TÀI CHÍNH (Page 14)
2.9 TRẠM Y TẾ (Page 14)
2.10 CHƯƠNG TRÌNH CHĂM SÓC SỨC KHỎE TINH THẦN NGƯỜI HỌC (Page 15)
2.11 THƯ VIỆN (Page 17)
2.11.1 SẢN PHẨM (Page 17)
2.11.2 DỊCH VỤ (Page 18)
2.11.3 QUY TRÌNH SỬ DỤNG THƯ VIỆN (Page 19)
3 CÁC KHOA (Page 21)
3.1 KHOA CÔNG NGHỆ THÔNG TIN (Page 21)
3.1.1 MỤC TIÊU ĐÀO TẠO (Page 21)
3.1.2 CÁC BỘ MÔN (Page 21)
3.1.3 CÁC LĨNH VỰC ĐÀO TẠO (Page 23)
3.1.4 CHƯƠNG TRÌNH CHĂM SÓC SỨC KHỎE TINH THẦN SINH VIÊN KHOA CÔNG NGHỆ THÔNG TIN GÓC SẺ CHIA - WE TALK (Page 24)
3.1.5 THÔNG TIN CÁC CHƯƠNG TRÌNH ĐÀO TẠO KHOA CÔNG NGHỆ THÔNG TIN (Page 25)
3.1.6 HỌC BỔNG (Page 26)
3.2 KHOA ĐỊA CHẤT (Page 27)
3.2.1 NGÀNH ĐỊA CHẤT HỌC (Page 27)
3.2.2 NGÀNH KỸ THUẬT ĐỊA CHẤT (Page 28)
3.2.3 NGÀNH KINH TẾ ĐẤT ĐAI (Page 28)
3.2.4 CHUẨN ĐẦU RA CHUNG KHOA ĐỊA CHẤT (Page 29)
3.2.5 TRÌNH ĐỘ NGOẠI NGỮ (Page 29)
3.3 KHOA HÓA HỌC (Page 30)
3.3.1 CHUẨN ĐẦU RA NGÀNH HÓA HỌC (Page 30)
3.3.2 CHƯƠNG TRÌNH CỬ NHÂN TÀI NĂNG - CHẤT LƯỢNG CAO (CHƯƠNG TRÌNH THEO ĐỀ ÁN) (Page 31)
3.3.3 NGÀNH CÔNG NGHỆ KỸ THUẬT HÓA HỌC (CHẤT LƯỢNG CAO) (Page 32)
3.3.4 CƠ HỘI NGHỀ NGHIỆP (Page 34)
3.3.5 CÁC ĐƠN VỊ CÓ HỢP TÁC VỚI KHOA (Page 34)
3.4 KHOA ĐIỆN TỬ - VIỄN THÔNG (Page 35)
3.4.1 CHUẨN ĐẦU RA (Page 35)
3.4.2 Kỹ năng và thái độ (Page 36)
3.5 KHOA KHOA HỌC VÀ CÔNG NGHỆ VẬT LIỆU (Page 37)
3.5.1 CƠ HỘI VIỆC LÀM (Page 37)
3.5.2 CHUẨN ĐẦU RA (Page 38)
3.5.2.1 NGÀNH KHOA HỌC VẬT LIỆU (Page 38)
3.5.2.2 NGÀNH CÔNG NGHỆ VẬT LIỆU (Page 38)
3.6 KHOA MÔI TRƯỜNG (Page 39)
3.6.1 CHUẨN ĐẦU RA CHUNG (Page 39)
3.6.2 ĐIỂM KHÁC BIỆT CỦA CÁC NGÀNH ĐÀO TẠO CỬ NHÂN (Page 40)
3.6.3 CƠ HỘI NGHỀ NGHIỆP (Page 41)
3.6.4 SAU KHI TỐT NGHIỆP KHOA MÔI TRƯỜNG SINH VIÊN CÓ THỂ LÀM? (Page 42)
3.7 KHOA SINH HỌC - CÔNG NGHỆ SINH HỌC (Page 43)
3.7.1 CHUẨN ĐẦU RA (Page 43)
3.7.2 ĐIỂM KHÁC BIỆT CỦA CÁC NGÀNH ĐÀO TẠO CỬ NHÂN (Page 44)
3.8 KHOA TOÁN - TIN HỌC (Page 45)
3.8.1 CÁC NGÀNH ĐÀO TẠO (Page 45)
3.8.2 CƠ HỘI NGHỀ NGHIỆP (Page 46)
3.9 KHOA VẬT LÝ - VẬT LÝ KỸ THUẬT (Page 47)
3.9.1 CÁC NGÀNH ĐÀO TẠO (Page 47)
3.9.2 CHUẨN ĐẦU RA (Page 48)
3.10 KHOA KHOA HỌC LIÊN NGÀNH (Page 49)
3.10.1 CÁC NGÀNH ĐÀO TẠO (Page 49)
3.10.2 CƠ HỘI NGHỀ NGHIỆP (Page 49)
3.10.3 CHUẨN ĐẦU RA (Page 50)
4 ĐOÀN THANH NIÊN, HỘI SINH VIÊN, TRUNG TÂM HỖ TRỢ SINH VIÊN (Page 49)
4.1 ĐOÀN TNCS HỒ CHÍ MINH TRƯỜNG ĐẠI HỌC KHOA HỌC TỰ NHIÊN, ĐHQG-HCM (Page 51)
4.1.1 HOẠT ĐỘNG BỒI DƯỠNG, RÈN LUYỆN, CHĂM LO SINH VIÊN LÀM CÔNG TÁC ĐOÀN (Page 51)
4.2 HỘI SINH VIÊN VIỆT NAM TRƯỜNG ĐẠI HỌC KHOA HỌC TỰ NHIÊN, ĐHQG-HCM (Page 52)
4.2.1 HỌC THUẬT - KỸ NĂNG - HỘI NHẬP (Page 52)
4.2.2 PHONG TRÀO SINH VIÊN 5 TỐT (Page 52)
4.3 TRUNG TÂM HỖ TRỢ SINH VIÊN (Page 53)
5 TRUNG TÂM NGOẠI NGỮ (Page 54)
6 KẾ HOẠCH NĂM HỌC 2023 - 2024 (Page 55)
6.1 ĐẠI HỌC CHÍNH QUY - CHƯƠNG TRÌNH ĐẠI TRÀ (Dự kiến) (Page 55)
6.1.1 HỌC KỲ 1 (Page 55)
6.1.2 HỌC KỲ 2 (Page 56)
6.1.3 HỌC KỲ HÈ (Page 56)
6.2 ĐẠI HỌC CHÍNH QUY - CHƯƠNG TRÌNH ĐỀ ÁN (Dự kiến) (Page 57)
6.2.1 HỌC KỲ 1 (Page 57)
6.2.2 HỌC KỲ 2 (Page 58)
6.2.3 HỌC KỲ 3 (Page 58)
7 QUY CHẾ ĐÀO TẠO TRÌNH ĐỘ ĐẠI HỌC TRƯỜNG ĐH KHTN (Page 59)
7.1 CHƯƠNG I. NHỮNG QUY ĐỊNH CHUNG (Page 59)
7.1.1 Phạm vi điều chỉnh và đối tượng áp dụng (Page 59)
7.1.2 Chương trình đào tạo và thời gian học tập (Page 59)
7.1.3 Học phần, đề cương chi tiết học phần và tín chỉ (Page 61)
7.1.4 Phương thức tổ chức đào tạo (Page 62)
7.2 CHƯƠNG II. LẬP KẾ HOẠCH VÀ TỔ CHỨC GIẢNG DẠY (Page 64)
7.2.1 Kế hoạch giảng dạy và học tập (Page 64)
7.2.2 Tổ chức đăng ký học tập (Page 66)
7.2.3 Tổ chức giảng dạy và học tập (Page 68)
7.3 CHƯƠNG III. ĐÁNH GIÁ KẾT QUẢ HỌC TẬP VÀ CẤP BẰNG TỐT NGHIỆP (Page 69)
7.3.1 Đánh giá học phần (Page 69)
7.3.2 Đánh giá đồ án tốt nghiệp, khóa luận tốt nghiệp/thực tập tốt nghiệp/dự án tốt nghiệp (Page 70)
7.3.3 Tính điểm học phần (Page 72)
7.3.4 Hoãn thi (Page 73)
7.3.5 Công nhận kết quả học tập và chuyển đổi tín chỉ (miễn học) (Page 73)
7.3.6 Học lại và học cải thiện điểm (Page 74)
7.3.7 Đánh giá kết quả học tập theo học kỳ, năm học, khóa học (Page 75)
7.3.8 Xử lý kết quả học tập theo tín chỉ (Page 77)
7.3.9 Xét tốt nghiệp và công nhận tốt nghiệp (Page 78)
7.3.10 Cấp bằng tốt nghiệp (Page 79)
7.4 CHƯƠNG IV. NHỮNG QUY ĐỊNH KHÁC ĐỐI VỚI SINH VIÊN (Page 80)
7.4.1 Nghỉ học tạm thời, thôi học (Page 80)
7.4.2 Chuyển chương trình, chuyển trường (Page 81)
7.4.3 Trao đổi sinh viên và hợp tác trong đào tạo (Page 82)
7.4.4 Học cùng lúc hai chương trình (Page 83)
7.4.5 Xử lý vi phạm đối với sinh viên (Page 84)
8 TRÍCH LƯỢC QUY ĐỊNH CÔNG TÁC KHẢO THÍ TRƯỜNG ĐH KHTN (Page 85)
8.1 CHƯƠNG I. QUY ĐỊNH CHUNG (Page 85)
8.1.1 Phạm vi điều chỉnh và đối tượng áp dụng (Page 85)
8.1.2 Mục đích điều chỉnh (Page 85)
8.2 CHƯƠNG II. QUY ĐỊNH VỀ KIỂM TRA GIỮA KỲ (Page 86)
8.2.1 Hình thức, thời gian kiểm tra giữa kỳ (Page 86)
8.2.2 Đề thi kiểm tra giữa kỳ (Page 86)
8.2.3 Tổ chức coi thi và chấm thi giữa kỳ (Page 86)
8.3 CHƯƠNG III. TỔ CHỨC THI KẾT THÚC HỌC PHẦN (Page 87)
8.3.1 Đánh giá học phần và điều kiện dự thi kết thúc học phần (Page 87)
8.3.2 Công tác tổ chức thi kết thúc học phần (Page 88)
8.3.3 Đề thi kết thúc học phần (Page 88)
8.3.4 Công tác chấm thi kết thúc học phần (Page 89)
8.3.5 Chấm phúc khảo (Page 89)
8.3.6 Quản lý, lưu trữ điểm thi, bài thi (Page 90)
9 TRÍCH LƯỢC QUY ĐỊNH TRÁCH NHIỆM CỦA CÁN BỘ VÀ NGƯỜI HỌC TRONG CÁC KỲ THI (Page 91)
9.1 CHƯƠNG I. QUY ĐỊNH CHUNG (Page 91)
9.1.1 Phạm vi điều chỉnh và đối tượng áp dụng (Page 91)
9.1.2 Mục đích điều chỉnh (Page 91)
9.2 CHƯƠNG II. QUY ĐỊNH VỀ TRÁCH NHIỆM CỦA CÁN BỘ THAM GIA CÔNG TÁC THI VÀ CỦA NGƯỜI HỌC (Page 92)
9.2.1 Trách nhiệm của Cán bộ coi thi (CBCT) (Page 92)
9.2.2 Trách nhiệm của Cán bộ giám sát phòng thi (Page 93)
9.2.3 Trách nhiệm của Cán bộ thư ký thi (Page 94)
9.2.4 Trách nhiệm của Cán bộ phụ trách thi (Page 94)
9.2.5 Trách nhiệm của Cán bộ ra đề thi (Page 94)
9.2.6 Trách nhiệm của người học trong các buổi thi (Page 95)
9.3 CHƯƠNG III. HÌNH THỨC XỬ LÝ VI PHẠM (Page 96)
9.3.1 Xử lý đối với CBCT vi phạm quy chế thi (Page 96)
9.3.2 Xử lý đối với người học vi phạm quy chế thi (Page 97)
9.3.3 Thẩm quyền xử lý CBCT và người học vi phạm quy chế thi (Page 98)
9.4 CHƯƠNG IV. TỔ CHỨC THỰC HIỆN (Page 99)
9.4.1 Trách nhiệm thực hiện (Page 99)
9.4.2 Điều khoản thi hành (Page 99)
10 TRÍCH LƯỢC QUY CHẾ CÔNG TÁC SINH VIÊN (Page 100)
10.1 CHƯƠNG III. QUYỀN VÀ NHIỆM VỤ CỦA SINH VIÊN (Page 100)
10.1.1 Quyền của sinh viên (Page 100)
10.1.2 Nhiệm vụ của sinh viên (Page 102)
10.1.3 Các hành vi sinh viên không được làm (Page 103)
10.2 CHƯƠNG IV. NỘI DUNG VỀ CÔNG TÁC SINH VIÊN TẠI CƠ SỞ ĐÀO TẠO (Page 104)
10.2.1 Tổ chức các hoạt động giáo dục, tuyên truyền (Page 104)
10.2.2 Công tác quản lý sinh viên (Page 106)
10.2.3 Công tác hỗ trợ và dịch vụ sinh viên (Page 109)
10.2.4 Công tác báo cáo (Page 110)
10.3 CHƯƠNG V. ĐÁNH GIÁ KẾT QUẢ RÈN LUYỆN SINH VIÊN (Page 111)
10.3.1 Mục đích đánh giá rèn luyện sinh viên (Page 111)
10.3.2 Tổ chức thực hiện (Page 111)
10.4 CHƯƠNG VII. KHEN THƯỞNG VÀ KỶ LUẬT (Page 112)
10.4.1 Cấp khen thưởng (Page 112)
10.4.2 Hội đồng thi đua, khen thưởng và kỷ luật sinh viên (Page 112)
10.4.3 Đối tượng, quy trình xét khen thưởng cấp ĐHQG-HCM (Page 113)
11 PHỤ LỤC MỘT SỐ NỘI DUNG VI PHẠM VÀ KHUNG XỬ LÝ KỶ LUẬT SINH VIÊN (Page 114)
11.1 Nguyên tắc chung (Page 114)
11.2 Một số nội dung vi phạm và khung xử lý kỷ luật sinh viên (Page 114)
12 QUY CHẾ ĐÁNH GIÁ KẾT QUẢ RÈN LUYỆN SINH VIÊN HỆ CHÍNH QUY TRƯỜNG ĐH KHTN (Page 118)
12.1 CHƯƠNG I. NHỮNG QUY ĐỊNH CHUNG (Page 118)
12.1.1 Phạm vi điều chỉnh và đối tượng áp dụng (Page 118)
12.1.2 Mục đích việc đánh giá kết quả rèn luyện sinh viên (Page 118)
12.1.3 Nguyên tắc đánh giá (Page 118)
12.1.4 Nội dung đánh giá, thang điểm và đợt đánh giá (Page 119)
12.2 CHƯƠNG II. CÁC TIÊU CHÍ ĐÁNH GIÁ, THỜI GIAN VÀ CÁCH TÍNH KẾT QUẢ (Page 120)
12.2.1 Các tiêu chí đánh giá (Page 120)
12.2.2 Thời gian và cách tính kết quả (Page 122)
12.3 CHƯƠNG III. PHÂN LOẠI KẾT QUẢ RÈN LUYỆN (Page 122)
12.3.1 Phân loại kết quả rèn luyện (Page 122)
12.3.2 Phân loại sinh viên để đánh giá (Page 123)
12.4 CHƯƠNG IV. TỔ CHỨC ĐÁNH GIÁ VÀ SỬ DỤNG KẾT QUẢ ĐÁNH GIÁ (Page 124)
12.4.1 Quy trình đánh giá kết quả rèn luyện (Page 124)
12.4.2 Hội đồng đánh giá kết quả rèn luyện (Page 125)
12.4.3 Sử dụng kết quả (Page 126)
12.4.4 Quyền khiếu nại (Page 127)
13 PHỤ LỤC KHUNG ĐIỂM CHI TIẾT CỦA CÁC NỘI DUNG ĐÁNH GIÁ KẾT QUẢ RÈN LUYỆN SINH VIÊN (Page 128)
14 TRÍCH LƯỢC QUY ĐỊNH KHEN THƯỞNG KỶ LUẬT SINH VIÊN (Page 138)
14.1 CHƯƠNG I. NHỮNG QUY ĐỊNH CHUNG (Page 138)
14.1.1 Phạm vi điều chỉnh và đối tượng áp dụng (Page 138)
14.1.2 Mục đích, yêu cầu của công tác khen thưởng, kỷ luật SV (Page 138)
14.2 CHƯƠNG II. NỘI DUNG CỦA CÔNG TÁC KHEN THƯỞNG (Page 139)
14.2.1 Các hình thức triển khai công tác khen thưởng (Page 139)
14.2.2 Khen thưởng đầu vào kỳ xét tuyển Đại học (Page 139)
14.2.3 Khen thưởng học kỳ, năm học (Page 140)
14.2.4 Khen thưởng tốt nghiệp (Page 141)
14.2.5 Quy trình khen thưởng (Page 142)
14.2.6 Định mức khen thưởng (Page 143)
14.2.7 Quyền khiếu nại về khen thưởng (Page 143)
14.3 CHƯƠNG III. NỘI DUNG CỦA CÔNG TÁC KỶ LUẬT (Page 143)
14.3.1 Quy định về hình thức kỷ luật và nội dung vi phạm (Page 143)
14.3.2 Trình tự, thủ tục và hồ sơ xét kỷ luật (Page 145)
14.3.3 Chấm dứt hiệu lực của quyết định kỷ luật (Page 146)
14.3.4 Quyền khiếu nại về kỷ luật (Page 147)
14.4 PHỤC LỤC I. MỘT SỐ NỘI DUNG VI PHẠM VÀ KHUNG XỬ LÝ KỶ LUẬT SINH VIÊN (Page 147)
15 TRÍCH LƯỢC QUY CHẾ NGOẠI TRÚ, NỘI TRÚ (Page 155)
15.1 QUY CHẾ NGOẠI TRÚ CỦA HỌC SINH, SINH VIÊN CÁC TRƯỜNG ĐẠI HỌC, CAO ĐẲNG, TRUNG CẤP CHUYÊN NGHIỆP HỆ CHÍNH QUY (Page 155)
15.1.1 Quyền của học sinh, sinh viên ngoại trú (Page 155)
15.1.2 Nghĩa vụ của học sinh, sinh viên ngoại trú (Page 155)
15.1.3 Kiểm tra, khen thưởng, kỷ luật (Page 156)
15.2 QUY CHẾ CÔNG TÁC HỌC SINH, SINH VIÊN NỘI TRÚ TẠI CÁC CƠ SỞ GIÁO DỤC THUỘC HỆ THỐNG GIÁO DỤC QUỐC DÂN (Page 157)
15.2.1 Đối tượng ưu tiên tiếp nhận ở nội trú (Page 157)
15.2.2 Quyền của học sinh, sinh viên nội trú (Page 158)
15.2.3 Nghĩa vụ của học sinh, sinh viên nội trú (Page 158)
15.2.4 Các hành vi học sinh, sinh viên nội trú không được làm (Page 159)
15.2.5 Kiểm tra, khen thưởng, kỷ luật (Page 159)
16 NỘI QUY CƠ QUAN (Page 161)
16.1 ĐỐI TƯỢNG ÁP DỤNG (Page 161)
16.2 NHỮNG QUY ĐỊNH CHUNG (Page 161)
16.3 ĐỐI VỚI VIÊN CHỨC, NGƯỜI LAO ĐỘNG (Page 162)
16.4 ĐỐI VỚI NGƯỜI HỌC (Page 163)
16.5 ĐỐI VỚI KHÁCH (Page 164)
17 QUY ĐỊNH XÉT CẤP HỌC BỔNG KHUYẾN KHÍCH HỌC TẬP (Page 165)
17.1 Quy định chung (Page 165)
17.2 Điều kiện và cơ sở xét học bổng (Page 166)
17.3 Phân loại và định mức học bổng; Phân bổ học bổng (Page 167)
17.4 Quy trình xét cấp học bổng khuyến khích (Page 168)
17.5 Tổ chức thực hiện (Page 168)
17.6 Điều khoản thi hành (Page 168)
18 THÔNG TIN MIỄN GIẢM HỌC PHÍ, TRỢ CẤP XÃ HỘI, CHÍNH SÁCH SINH VIÊN DÂN TỘC THIỂU SỐ, CHÍNH SÁCH SINH VIÊN DÂN TỘC THIỂU SỐ RẤT ÍT NGƯỜI, CHÍNH SÁCH SINH VIÊN KHUYẾT TẬT (Page 168)
18.1 THÔNG TIN MIỄN GIẢM HỌC PHÍ (Page 168)
18.1.1 Đối tượng được miễn 100% học phí (Page 168)
18.1.2 Đối tượng được giảm 70% học phí (Page 168)
18.1.3 Đối tượng được giảm 50% học phí (Page 169)
18.1.4 Thủ tục, hồ sơ (Page 169)
18.2 THÔNG TIN TRỢ CẤP XÃ HỘI (Page 170)
18.2.1 Đối tượng được trợ cấp 100.000đ/tháng (Page 170)
18.2.2 Đối tượng được trợ cấp 140.000đ/tháng (Page 170)
18.2.3 Thủ tục, hồ sơ (Page 170)
18.3 CHÍNH SÁCH SINH VIÊN DÂN TỘC THIỂU SỐ (Page 171)
18.3.1 Đối tượng (Page 171)
18.3.2 Chính sách về học phí (MGHP) (Page 171)
18.3.3 Chính sách về hỗ trợ (Page 171)
18.3.4 Thủ tục hồ sơ (nộp 01 bộ hồ sơ khác với hồ sơ MGHP) (Page 171)
18.4 CHÍNH SÁCH SINH VIÊN DÂN TỘC THIỂU SỐ RẤT ÍT NGƯỜI (Page 172)
18.4.1 Đối tượng (Page 172)
18.4.2 Chính sách về học phí (MGHP) (Page 172)
18.4.3 Chính sách về hỗ trợ (Page 172)
18.4.4 Thủ tục hồ sơ (nộp 01 bộ hồ sơ khác với hồ sơ MGHP) (Page 172)
18.5 CHÍNH SÁCH SINH VIÊN KHUYẾT TẬT (Page 173)
18.5.1 Đối tượng (Page 173)
18.5.2 Chính sách về học phí (MGHP) (Page 173)
18.5.3 Chính sách về Trợ cấp xã hội (TCXH) (Page 173)
18.5.4 Chính sách về học bổng (Page 173)
18.5.5 Chính sách về hỗ trợ phương tiện và đồ dùng học tập (Page 173)
18.5.6 Thủ tục hồ sơ (nộp 01 bộ hồ sơ khác với hồ sơ MGHP và TCXH) (Page 173)
19 DANH MỤC ĐIỆN THOẠI CÁC TỔ ĐẢM BẢO AN NINH TRẬT TỰ TRƯỜNG, ĐƠN VỊ (Page 174)
19.1 Danh mục SĐT tổ An ninh và đội bảo vệ Trường ĐH KHTN (Page 174)
19.2 Trung tâm Quản lý và Phát triển khu Đô thị ĐH Quốc gia TP. HCM (Page 174)
19.3 Chốt Dân phòng phường Đông Hòa tại khu Đô thị ĐHQG-HCM (Page 175)
19.4 Công an phường Đông Hòa - thị xã Dĩ An- Bình Dương (Page 175)
19.5 Công an phường Linh Trung - quận Thủ Đức - TP. HCM (Page 175)
19.6 Công an thành phố Dĩ An (Page 175)
19.7 Quản lý Ký túc xá (Page 176)
20 MỘT VÀI MÁCH NHỎ TÂN SINH VIÊN (Page 177)
20.1 CHUẨN BỊ BẢN SAO (CÓ CHỨNG THỰC) CỦA CÁC GIẤY TỜ CẦN THIẾT (Page 177)
20.2 XEM THÔNG TIN TRÊN WEBSITE TRƯỜNG THƯỜNG XUYÊN (Page 177)
20.3 THI GIẤY PHÉP LÁI XE (Page 177)
20.4 NỘI TRÚ KÝ TÚC XÁ (Page 178)
20.5 ĐẢM BẢO HỢP ĐỒNG THUÊ VÀ ĐĂNG KÝ TẠM TRÚ KHI THUÊ NHÀ TRỌ (Page 178)
20.6 ĐĂNG KÝ HỘ CHIẾU (Page 179)
20.7 LƯU Ý SINH VIÊN VỀ AN TOÀN (Page 180)
20.7.1 BẢO QUẢN TÀI SẢN CÁ NHÂN (Page 180)
20.7.2 CẢNH GIÁC VỚI CÁC THỦ ĐOẠN LỪA ĐẢO (Page 180)
20.7.3 TRÁNH SA ĐÀ VÀO TỆ NẠN XÃ HỘI (Page 181)
21 CÁC TUYẾN XE BUÝT LƯU THÔNG TRONG KHU ĐHQG-HCM (Page 182)"""

if __name__ == "__main__":
    logger.info("===============================================")
    logger.info("TEST SCRIPT EXECUTION START")
    logger.info("===============================================")
    
    success = test_quiz_generation()
    
    if success:
        logger.info("===============================================")
        logger.info("TEST SCRIPT EXECUTION COMPLETED SUCCESSFULLY")
        logger.info("===============================================")
    else:
        logger.error("===============================================")
        logger.error("TEST SCRIPT EXECUTION FAILED")
        logger.error("===============================================")

